spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Hey, welcome to EazyBank loans related prod APIs "
  contactDetails:
    name: "Pelias Sudhir - Product Owner"
    email: "pelias@eazybank.com"
  onCallSupport:
    - (723) 656-870991111
    - (156) 342-095661111
